replicaCount: 2

image:
  repository: vandu0409/my-java-app
  tag: "latest"
  pullPolicy: IfNotPresent
  # Optional imagePullSecrets: ["regcred"]

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources: {}
# e.g.
# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 200m
#     memory: 256Mi

env: []
# Example:
# env:
#   - name: SPRING_PROFILES_ACTIVE
#     value: production

livenessProbe:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    # Example for ingress nginx: enable rewrite etc if needed
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: my-java-app.example.com
      paths:
        - path: /
          # use prefix for pathType
          pathType: Prefix
  tls: []
  # Example TLS:
  # tls:
  #   - hosts:
  #       - my-java-app.example.com
  #     secretName: my-java-app-tls

podAnnotations: {}
