apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-java-app.fullname" . }}
  labels:
    {{- include "my-java-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-java-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-java-app.fullname" . }}
    spec:
      containers:
        - name: {{ include "my-java-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "my-java-app.fullname" . }}-config
                  key: APP_MESSAGE

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-java-app.fullname" . }}-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
