apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-java-app.fullname" . }}-secret
type: Opaque
data:
  DB_PASSWORD: {{ default "dmFuMTIzNDU=" (index .Values.secret "DB_PASSWORD") | quote }}


