apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-java-app.fullname" . }}-secret
type: Opaque
data:
  # Example: base64 encode your password and put here
  DB_PASSWORD: {{ default "dmFuMTIzNDU=" .Values.secret.DB_PASSWORD | quote }}

